import { RenovationProject } from '@/types/renovation';
import { getDefaultWorkStagesForRoom } from './progress-helper';

export const INITIAL_RENOVATION_PROJECT: RenovationProject = {
  id: 'renovai-proj-01',
  title: 'Mieszkanie 64m² - Modern Loft',
  address: 'ul. Grzybowska 43, Warszawa',
  totalPlannedBudget: 95000,
  contingencyReservePercent: 15,
  startDate: '2026-09-01',
  targetEndDate: '2026-11-20',
  selectedRoomId: 'room-bathroom',
  activeStep: 'photo_scan',
  isOfflineMode: false,
  e2eeEnabled: true,
  lastSyncedAt: 'Dziś, 10:45',
  rooms: [
    {
      id: 'room-bathroom',
      name: 'Łazienka z Walk-In',
      type: 'lazienka',
      width: 2.45,
      length: 2.55,
      height: 2.65,
      area: 6.25,
      wallArea: 23.8,
      perimeter: 10.0,
      workStages: getDefaultWorkStagesForRoom('lazienka', 'room-bathroom'),
      notes: 'Odpływ liniowy posadzkowy, hydroizolacja 2-warstwowa, stelaż podtynkowy WC, bateria podtynkowa czarny mat.',
      photoUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80',
      beforePhotoUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
      afterPhotoUrl: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=800&q=80',
      design: {
        floorType: 'Gres wielkoformatowy 120x60 kamień grafit',
        floorColor: '#334155',
        wallType: 'Płytki rektyfikowane lastryko + gładź ceramiczna',
        wallColor: '#cbd5e1',
        ceilingColor: '#f8fafc',
        lightingTempK: 4000,
      },
      openings: [
        { id: 'op-b1', type: 'door', name: 'Drzwi bezprzylgowe 80cm', width: 0.85, height: 2.05 },
      ],
      furniture: [
        { id: 'furn-b1', name: 'Kabina Walk-In z szybą 100cm', x: 12, y: 12, width: 38, height: 42, rotation: 0, iconType: 'shower' },
        { id: 'furn-b2', name: 'Stelaż podtynkowy WC', x: 68, y: 12, width: 24, height: 20, rotation: 0, iconType: 'toilet' },
        { id: 'furn-b3', name: 'Szafka z umywalką nablatową 80cm', x: 55, y: 55, width: 35, height: 28, rotation: 0, iconType: 'sink' },
        { id: 'furn-b4', name: 'Pralka w zabudowie', x: 12, y: 65, width: 26, height: 25, rotation: 0, iconType: 'washer' },
      ],
      outlets: [
        { id: 'out-b1', type: 'water_in', label: 'Zasilanie baterii prysznicowej', x: 28, y: 15 },
        { id: 'out-b2', type: 'water_out', label: 'Odpływ liniowy 80cm', x: 30, y: 35 },
        { id: 'out-b3', type: 'socket', label: 'Gniazdo bryzgoszczelne IP44 (lustro)', x: 70, y: 72 },
        { id: 'out-b4', type: 'light_switch', label: 'Włącznik podświetlenia LED', x: 88, y: 90 },
      ],
      detectedEntities: [
        { id: 'det-1', name: 'Ściana nośna lewa', category: 'wall', confidence: 0.98, boundingBox: { x: 5, y: 10, width: 25, height: 80 }, details: 'Tynk cementowo-wapienny, wymaga skucia starych płytek' },
        { id: 'det-2', name: 'Posadzka (strefa odpływu)', category: 'floor', confidence: 0.95, boundingBox: { x: 10, y: 60, width: 80, height: 35 }, details: 'Konieczne wykonanie spadku 2% do rynny odpływowej' },
        { id: 'det-3', name: 'Pion kanalizacyjny i wodomierze', category: 'installation', confidence: 0.92, boundingBox: { x: 72, y: 15, width: 22, height: 50 }, details: 'Wymagana rewizja z drzwiczkami magnetycznymi' },
        { id: 'det-4', name: 'Otwór drzwiowy', category: 'door', confidence: 0.99, boundingBox: { x: 40, y: 2, width: 20, height: 30 }, details: 'Ościeżnica ukryta, otwór 90x210 cm w stanie surowym' },
      ],
    },
    {
      id: 'room-living',
      name: 'Salon z aneksem',
      type: 'salon',
      width: 4.80,
      length: 5.90,
      height: 2.65,
      area: 28.32,
      wallArea: 48.5,
      perimeter: 21.4,
      workStages: getDefaultWorkStagesForRoom('salon', 'room-living'),
      notes: 'Otwarta przestrzeń dzienna, podłoga dąb naturalny jodełka, wyspa kuchenna z płytą indukcyjną i pochłaniaczem.',
      photoUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      beforePhotoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
      afterPhotoUrl: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',
      design: {
        floorType: 'Drewno dąb naturalny - deska w jodełkę klasyczną',
        floorColor: '#b48256',
        wallType: 'Farba ceramiczna matowa RAL 9003 + beton architektoniczny',
        wallColor: '#e2e8f0',
        ceilingColor: '#ffffff',
        accentWallColor: '#334155',
        lightingTempK: 2700,
      },
      openings: [
        { id: 'op-l1', type: 'window', name: 'Okno balkonowe HS 240x220', width: 2.4, height: 2.2 },
        { id: 'op-l2', type: 'window', name: 'Okno kuchenne 120x140', width: 1.2, height: 1.4 },
        { id: 'op-l3', type: 'door', name: 'Wejście z holu', width: 1.2, height: 2.1 },
      ],
      furniture: [
        { id: 'furn-l1', name: 'Narożnik modułowy', x: 55, y: 45, width: 35, height: 45, rotation: 0, iconType: 'sofa' },
        { id: 'furn-l2', name: 'Wyspa kuchenna z hokerami', x: 15, y: 35, width: 28, height: 35, rotation: 0, iconType: 'kitchen' },
        { id: 'furn-l3', name: 'Szafka RTV i ekran OLED', x: 65, y: 10, width: 25, height: 12, rotation: 0, iconType: 'tv' },
      ],
      outlets: [
        { id: 'out-l1', type: 'socket', label: 'Zasilanie indukcji 400V 3N~', x: 18, y: 40 },
        { id: 'out-l2', type: 'socket', label: 'Gniazda blatowe podszafkowe 4x', x: 10, y: 15 },
        { id: 'out-l3', type: 'light_switch', label: 'Szynoprzewody magnetyczne LED', x: 85, y: 88 },
      ],
      detectedEntities: [
        { id: 'det-l1', name: 'Ściana pod TV', category: 'wall', confidence: 0.99, boundingBox: { x: 50, y: 10, width: 45, height: 50 }, details: 'Wymaga poprowadzenia peszli pod przewody HDMI/optyczne' },
        { id: 'det-l2', name: 'Wylewka jastrychowa', category: 'floor', confidence: 0.96, boundingBox: { x: 5, y: 45, width: 90, height: 50 }, details: 'Wilgotność 1.4% CM - gotowa pod montaż deski klejonej' },
      ],
    },
    {
      id: 'room-bedroom',
      name: 'Sypialnia Master',
      type: 'sypialnia',
      width: 3.40,
      length: 4.25,
      height: 2.65,
      area: 14.45,
      wallArea: 35.8,
      perimeter: 15.3,
      workStages: getDefaultWorkStagesForRoom('sypialnia', 'room-bedroom'),
      notes: 'Garderoba w zabudowie sufitowej, lamele akustyczne za wezgłowiem łóżka, zaciemniające rolety kasetowe.',
      photoUrl: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=1200&q=80',
      design: {
        floorType: 'Wykładzina welurowa na podkładzie piankowym',
        floorColor: '#94a3b8',
        wallType: 'Farba lateksowa ciepły piasek + lamele dębowe',
        wallColor: '#f1f5f9',
        ceilingColor: '#ffffff',
        lightingTempK: 2700,
      },
      openings: [
        { id: 'op-be1', type: 'window', name: 'Okno trzyszybowe 160x145', width: 1.6, height: 1.45 },
        { id: 'op-be2', type: 'door', name: 'Drzwi wewnętrzne 80cm', width: 0.85, height: 2.05 },
      ],
      furniture: [
        { id: 'furn-be1', name: 'Łóżko 160x200 z pojemnikiem', x: 25, y: 25, width: 45, height: 50, rotation: 0, iconType: 'bed' },
        { id: 'furn-be2', name: 'Szafa garderobiana przesuwna', x: 5, y: 80, width: 85, height: 15, rotation: 0, iconType: 'wardrobe' },
      ],
      outlets: [
        { id: 'out-be1', type: 'socket', label: 'Gniazda przy łóżku lewa/prawa', x: 20, y: 30 },
        { id: 'out-be2', type: 'light_switch', label: 'Włącznik schodowy oświetlenia nocnego', x: 80, y: 80 },
      ],
      detectedEntities: [
        { id: 'det-be1', name: 'Ściana wezgłowia', category: 'wall', confidence: 0.98, boundingBox: { x: 20, y: 5, width: 60, height: 60 }, details: 'Ściana wygłuszona wełną mineralną 5cm i podwójnym GK' },
      ],
    },
    {
      id: 'room-hallway',
      name: 'Przedpokój / Hol',
      type: 'przedpokoj',
      width: 2.20,
      length: 3.70,
      height: 2.65,
      area: 8.14,
      wallArea: 27.5,
      perimeter: 11.8,
      workStages: getDefaultWorkStagesForRoom('przedpokoj', 'room-hallway'),
      notes: 'Rozdzielnica elektryczna Hager 4x18 modułów, płytki gresowe przy wejściu płynnie połączone z deską.',
      photoUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      design: {
        floorType: 'Gres wielkoformatowy matowy 80x80',
        floorColor: '#64748b',
        wallType: 'Tynk strukturalny zmywalny',
        wallColor: '#e2e8f0',
        ceilingColor: '#ffffff',
        lightingTempK: 4000,
      },
      openings: [
        { id: 'op-h1', type: 'door', name: 'Drzwi wejściowe antywłamaniowe RC3', width: 1.0, height: 2.1 },
      ],
      furniture: [
        { id: 'furn-h1', name: 'Szafa z lustrem i siedziskiem', x: 10, y: 20, width: 40, height: 60, rotation: 0, iconType: 'wardrobe' },
      ],
      outlets: [
        { id: 'out-h1', type: 'socket', label: 'Główna rozdzielnica teletechniczna i 230V', x: 75, y: 25 },
      ],
      detectedEntities: [
        { id: 'det-h1', name: 'Strefa wejściowa brudna', category: 'floor', confidence: 0.97, boundingBox: { x: 5, y: 5, width: 90, height: 40 }, details: 'Dedykowana strefa z matą grzewczą na osuszanie butów' },
      ],
    },
  ],
  stages: [
    {
      id: 'st-1',
      name: 'Demontaże i skucie starych okładzin',
      category: 'demolition',
      status: 'done',
      progressPercent: 100,
      startDate: '2026-09-01',
      endDate: '2026-09-05',
      isDiy: true,
      contractorCostEstimate: 4500,
      diyCostEstimate: 1400,
      requiredTools: ['Młot udarowo-obrotowy SDS+', 'Łom stalowy', 'Worki big-bag', 'Odkurzacz przemysłowy'],
      safetyGear: ['Okulary ochronne', 'Maska przeciwpyłowa FFP3', 'Rękawice wzmacniane', 'Ochronniki słuchu'],
      tasks: [
        { id: 't-1-1', title: 'Skucie starych płytek w łazience i kuchni', completed: true },
        { id: 't-1-2', title: 'Demontaż starej armatury i mebli', completed: true },
        { id: 't-1-3', title: 'Wywóz gruzu kontenerem 5m³', completed: true },
      ],
      description: 'Bezpieczne usunięcie starych warstw bez naruszenia konstrukcji nośnych budynku.',
    },
    {
      id: 'st-2',
      name: 'Przeróbki hydrauliczne i kanalizacyjne',
      category: 'installation',
      status: 'done',
      progressPercent: 100,
      startDate: '2026-09-06',
      endDate: '2026-09-10',
      isDiy: false,
      contractorCostEstimate: 4800,
      diyCostEstimate: 2100,
      requiredTools: ['Zaciskarka do rur PEX', 'Poziomica laserowa 3D', 'Bruzdownica z odsyłaniem pyłu'],
      safetyGear: ['Rękawice montażowe', 'Maska pyłowa'],
      tasks: [
        { id: 't-2-1', title: 'Montaż odpływu liniowego z kołnierzem', completed: true },
        { id: 't-2-2', title: 'Podejścia pod baterie podtynkowe (Geberit + prysznic)', completed: true },
        { id: 't-2-3', title: 'Próba ciśnieniowa 10 barów przez 24h', completed: true },
      ],
      description: 'Nowoczesny system rozdzielaczowy PEX-AL-PEX bez połączeń pod posadzką.',
    },
    {
      id: 'st-3',
      name: 'Nowa instalacja elektryczna i teletechniczna',
      category: 'installation',
      status: 'done',
      progressPercent: 100,
      startDate: '2026-09-11',
      endDate: '2026-09-16',
      isDiy: false,
      contractorCostEstimate: 6500,
      diyCostEstimate: 3200,
      requiredTools: ['Bruzdownica', 'Otwornica do puszek fi 68mm', 'Miernik wielofunkcyjny instalacji'],
      safetyGear: ['Rękawice dielektryczne', 'Okulary ochronne'],
      tasks: [
        { id: 't-3-1', title: 'Prowadzenie tras kablowych w peszlach', completed: true },
        { id: 't-3-2', title: 'Montaż głębokich puszek pod smart home', completed: true },
        { id: 't-3-3', title: 'Uzbrojenie rozdzielnicy głównej z RCD i SPD', completed: true },
      ],
      description: 'Podział na dedykowane obwody: płyta indukcyjna, zmywarka, pralka, gniazda ogólne, oświetlenie.',
    },
    {
      id: 'st-4',
      name: 'Hydroizolacja łazienki i wylewka samopoziomująca',
      category: 'insulation',
      roomId: 'room-bathroom',
      status: 'waiting_cure',
      progressPercent: 85,
      startDate: '2026-09-17',
      endDate: '2026-09-20',
      curingTimeHours: 24,
      curingHoursRemaining: 18,
      isDiy: true,
      contractorCostEstimate: 2200,
      diyCostEstimate: 750,
      requiredTools: ['Wałek welurowy', 'Paca zębata', 'Taśma uszczelniająca z mankietami', 'Mieszadło wolnoobrotowe'],
      safetyGear: ['Kombinezon malarski', 'Rękawice nitrylowe'],
      tasks: [
        { id: 't-4-1', title: 'Gruntowanie podłoża preparatem głęboko penetrującym', completed: true },
        { id: 't-4-2', title: 'Wklejenie taśm uszczelniających w naroża i kołnierze', completed: true },
        { id: 't-4-3', title: 'Druga warstwa folii w płynie (krzyżowo)', completed: true },
        { id: 't-4-4', title: 'Odczekanie pełnego czasu wiązania (24h) przed kafelkowaniem', completed: false },
      ],
      description: 'Zapewnienie 100% szczelności strefy mokrej (kabina, strefa umywalki, posadzka łazienki).',
    },
    {
      id: 'st-5',
      name: 'Układanie gresu wielkoformatowego (120x60)',
      category: 'finishing',
      roomId: 'room-bathroom',
      status: 'in_progress',
      progressPercent: 45,
      startDate: '2026-09-21',
      endDate: '2026-09-27',
      isDiy: false,
      contractorCostEstimate: 5500,
      diyCostEstimate: 1900,
      requiredTools: ['Przecinarka do gresu 130cm', 'System poziomowania płytek (klipsy i kliny)', 'Przyssawka wibracyjna do płytek'],
      safetyGear: ['Nakolanniki żelowe', 'Rękawice ochronne', 'Okulary'],
      tasks: [
        { id: 't-5-1', title: 'Rozplanowanie symetrii i docinek narożnych', completed: true },
        { id: 't-5-2', title: 'Układanie posadzki ze spadkiem do odpływu', completed: true },
        { id: 't-5-3', title: 'Montaż płytek ściennych z fazowaniem 45°', completed: false },
        { id: 't-5-4', title: 'Spoinowanie fugą epoksydową odporną na pleśń', completed: false },
      ],
      description: 'Precyzyjny montaż gresu rektyfikowanego na kleju elastycznym C2TE S1 z metodą podwójnego smarowania (buttering-floating).',
    },
    {
      id: 'st-6',
      name: 'Gładzie gipsowe bezpyłowe Q3/Q4 i gruntowanie',
      category: 'masonry',
      status: 'planned',
      progressPercent: 0,
      startDate: '2026-09-28',
      endDate: '2026-10-06',
      isDiy: true,
      contractorCostEstimate: 4200,
      diyCostEstimate: 1100,
      requiredTools: ['Szlifierka do gipsu (żyrafa) z odkurzaczem', 'Paca ze stali nierdzewnej 40cm', 'Lampa inspekcyjna Smugi-Zero'],
      safetyGear: ['Maska lakiernicza/przeciwpyłowa P3', 'Gogle ochronne'],
      tasks: [
        { id: 't-6-1', title: 'Wtopienie taśm fizelinowych na łączeniach i pęknięciach', completed: false },
        { id: 't-6-2', title: 'Aplikacja gładzi polimerowej 2 warstwy', completed: false },
        { id: 't-6-3', title: 'Szlifowanie bezpyłowe z lampą smugową', completed: false },
        { id: 't-6-4', title: 'Odpylenie i gruntowanie pod malowanie', completed: false },
      ],
      description: 'Idealnie gładka powierzchnia ścian i sufitów przygotowana pod oświetlenie boczne LED.',
    },
    {
      id: 'st-7',
      name: 'Malowanie ścian i sufitów',
      category: 'finishing',
      status: 'planned',
      progressPercent: 0,
      startDate: '2026-10-07',
      endDate: '2026-10-12',
      isDiy: true,
      contractorCostEstimate: 3200,
      diyCostEstimate: 850,
      requiredTools: ['Agregat malarski lub wałki z mikrofibry 18mm', 'Taśmy malarskie washi gold', 'Kuweta z wkładami'],
      safetyGear: ['Ubranie ochronne', 'Rękawice lateksowe'],
      tasks: [
        { id: 't-7-1', title: 'Malowanie sufitów na matową biel antyrefleksyjną', completed: false },
        { id: 't-7-2', title: 'Precyzyjne odcięcia kolorów taśmą premium', completed: false },
        { id: 't-7-3', title: 'Malowanie ścian farbami ceramicznymi klasa 1', completed: false },
      ],
      description: 'Aplikacja farb ceramicznych odpornych na szorowanie na mokro w odcieniach loftowych.',
    },
    {
      id: 'st-8',
      name: 'Montaż podłóg drewnianych i listew przypodłogowych',
      category: 'flooring',
      roomId: 'room-living',
      status: 'planned',
      progressPercent: 0,
      startDate: '2026-10-13',
      endDate: '2026-10-18',
      isDiy: false,
      contractorCostEstimate: 3800,
      diyCostEstimate: 1200,
      requiredTools: ['Ukośnica z tarczą do drewna 60T', 'Klej poliuretanowo-silanowy do parkietu', 'Klocki dociskowe'],
      safetyGear: ['Okulary ochronne', 'Rękawice robocze'],
      tasks: [
        { id: 't-8-1', title: 'Sprawdzenie wilgotności posadzki metodą CM (<1.8%)', completed: false },
        { id: 't-8-2', title: 'Klejenie deski w jodełkę klasyczną', completed: false },
        { id: 't-8-3', title: 'Montaż listew MDF na klej montażowy polimerowy', completed: false },
      ],
      description: 'Trwały montaż klejony gwarantujący ciche użytkowanie i współpracę z ogrzewaniem.',
    },
    {
      id: 'st-9',
      name: 'Biały montaż, armatura i oświetlenie',
      category: 'finishing',
      status: 'planned',
      progressPercent: 0,
      startDate: '2026-10-19',
      endDate: '2026-10-25',
      isDiy: true,
      contractorCostEstimate: 2900,
      diyCostEstimate: 600,
      requiredTools: ['Zestaw kluczy nastawnych z nakładkami teflonowymi', 'Wkrętarka akumulatorowa', 'Pistolet do silikonu sanitarnego'],
      safetyGear: ['Rękawice monterskie'],
      tasks: [
        { id: 't-9-1', title: 'Montaż miski WC rimless z deską wolnoopadającą', completed: false },
        { id: 't-9-2', title: 'Montaż baterii podtynkowych i deszczownicy', completed: false },
        { id: 't-9-3', title: 'Silikonowanie sanitarne z neutralnym utwardzaniem', completed: false },
        { id: 't-9-4', title: 'Montaż szynoprzewodów magnetycznych i opraw LED', completed: false },
      ],
      description: 'Zwieńczenie prac sanitarnych i oświetleniowych.',
    },
  ],
  materials: [
    {
      id: 'mat-1',
      roomId: 'room-bathroom',
      name: 'Gres wielkoformatowy 120x60 cm kamień grafit',
      category: 'płytki',
      formulaExplanation: 'Powierzchnia podłogi (6.25 m²) + docinki narożne 15% zapasu',
      baseQuantity: 6.25,
      wasteMarginPercent: 15,
      finalQuantity: 7.2,
      unit: 'm²',
      estimatedUnitPrice: 139,
      totalPrice: 1000.80,
      purchased: true,
      brandProduct: 'Tubądzin Korzilius Graphite 119.8x59.8',
    },
    {
      id: 'mat-2',
      roomId: 'room-bathroom',
      name: 'Klej elastyczny odkształcalny C2TE S1 (worek 25kg)',
      category: 'chemia_budowlana',
      formulaExplanation: '4.5 kg/m² dla płyt wielkoformatowych przy pacy 10mm × 7.2 m² = 32.4 kg (2 worki)',
      baseQuantity: 32.4,
      wasteMarginPercent: 10,
      finalQuantity: 2,
      unit: 'opak.',
      estimatedUnitPrice: 68,
      totalPrice: 136,
      purchased: true,
      brandProduct: 'Atlas Geoflex S1 / Mapei Keraflex Maxi',
    },
    {
      id: 'mat-3',
      roomId: 'room-bathroom',
      name: 'Hydroizolacja 2-składnikowa elastyczna (wiadro 12kg)',
      category: 'chemia_budowlana',
      formulaExplanation: '1.4 kg/m² dla 2 warstw × strefa mokra 16 m² = 22.4 kg (2 wiadra)',
      baseQuantity: 22.4,
      wasteMarginPercent: 10,
      finalQuantity: 2,
      unit: 'opak.',
      estimatedUnitPrice: 185,
      totalPrice: 370,
      purchased: true,
      brandProduct: 'Mapei Mapelastic AquaDefense',
    },
    {
      id: 'mat-4',
      roomId: 'room-living',
      name: 'Deska warstwowa dębowa - jodełka klasyczna',
      category: 'podłogi',
      formulaExplanation: 'Powierzchnia salonu (28.32 m²) + układ w jodełkę wymaga min. 12% naddatku na docinki skrajne',
      baseQuantity: 28.32,
      wasteMarginPercent: 12,
      finalQuantity: 31.8,
      unit: 'm²',
      estimatedUnitPrice: 210,
      totalPrice: 6678,
      purchased: false,
      brandProduct: 'Barlinek Pure Line Herringbone Dąb Caramel',
    },
    {
      id: 'mat-5',
      roomId: 'room-living',
      name: 'Klej hybrydowy do parkietu i deski (wiadro 15kg)',
      category: 'chemia_budowlana',
      formulaExplanation: 'Średnie zużycie pacy zębatej B11 to 1.1 kg/m² × 31.8 m² = 35 kg (3 wiadra)',
      baseQuantity: 35,
      wasteMarginPercent: 5,
      finalQuantity: 3,
      unit: 'opak.',
      estimatedUnitPrice: 290,
      totalPrice: 870,
      purchased: false,
      brandProduct: 'Bona Quantum / Wakol MS 260',
    },
    {
      id: 'mat-6',
      roomId: 'room-living',
      name: 'Farba ceramiczna odporna na plamy (puszka 5L)',
      category: 'ściany',
      formulaExplanation: 'Powierzchnia ścian (48.5 m²) × 2 warstwy ÷ wydajność 14 m²/L = 6.9 L (2 puszki)',
      baseQuantity: 6.9,
      wasteMarginPercent: 10,
      finalQuantity: 2,
      unit: 'opak.',
      estimatedUnitPrice: 165,
      totalPrice: 330,
      purchased: false,
      brandProduct: 'Beckers Designer White / Tikkurila Optiva 5',
    },
    {
      id: 'mat-7',
      roomId: 'room-bathroom',
      name: 'Odpływ liniowy szczelinowy z kołnierzem 80cm',
      category: 'hydraulika',
      formulaExplanation: '1 sztuka dopasowana do wnęki prysznicowej Walk-In',
      baseQuantity: 1,
      wasteMarginPercent: 0,
      finalQuantity: 1,
      unit: 'szt.',
      estimatedUnitPrice: 790,
      totalPrice: 790,
      purchased: true,
      brandProduct: 'Viega Advantix Cleviva 800mm',
    },
    {
      id: 'mat-8',
      roomId: 'room-living',
      name: 'Listwy przypodłogowe MDF lakierowane 80mm',
      category: 'stolarka',
      formulaExplanation: 'Obwód ścian 21.4 mb - otwory drzwiowe 3.6 mb = 17.8 mb + 10% skosy = 20 mb (8 listew po 2.5m)',
      baseQuantity: 17.8,
      wasteMarginPercent: 10,
      finalQuantity: 8,
      unit: 'szt.',
      estimatedUnitPrice: 42,
      totalPrice: 336,
      purchased: false,
      brandProduct: 'Lagrus Plus 80 Biały Półmat',
    },
  ],
  expenses: [
    {
      id: 'exp-1',
      title: 'Zaliczka na gres łazienkowy i płytki ścienne',
      amount: 3450,
      date: '2026-09-02',
      category: 'Materiały budowlane',
      roomId: 'room-bathroom',
      paid: true,
      paymentMethod: 'Karta / Przelew',
      receiptNote: 'Faktura VAT 421/2026 - Salon Glazury',
      hasAttachment: true,
    },
    {
      id: 'exp-2',
      title: 'Wynajem kontenera na gruz 5m³ z utylizacją',
      amount: 1100,
      date: '2026-09-03',
      category: 'Wywóz gruzu i utylizacja',
      paid: true,
      paymentMethod: 'BLIK',
      receiptNote: 'Faktura GruzMax sp. z o.o.',
      hasAttachment: true,
    },
    {
      id: 'exp-3',
      title: 'Kleje, taśmy uszczelniające, folia w płynie Mapei',
      amount: 1240,
      date: '2026-09-07',
      category: 'Materiały budowlane',
      roomId: 'room-bathroom',
      paid: true,
      paymentMethod: 'Karta / Przelew',
      receiptNote: 'Castorama Warszawa - Paragon z NIP',
      hasAttachment: true,
    },
    {
      id: 'exp-4',
      title: 'Robocizna: Przeróbki hydrauliczne i próba ciśnieniowa',
      amount: 3800,
      date: '2026-09-10',
      category: 'Robocizna / Ekipa',
      roomId: 'room-bathroom',
      paid: true,
      paymentMethod: 'Karta / Przelew',
      receiptNote: 'Protokół odbioru prac hydraulicznych',
      hasAttachment: true,
    },
    {
      id: 'exp-5',
      title: 'Przewody YDYp, peszle, rozdzielnica Hager, osprzęt',
      amount: 2450,
      date: '2026-09-12',
      category: 'Materiały budowlane',
      paid: true,
      paymentMethod: 'Karta / Przelew',
      receiptNote: 'Hurtownia Elektryczna TIM',
      hasAttachment: false,
    },
    {
      id: 'exp-6',
      title: 'Robocizna: Wykonanie instalacji elektrycznej pod smart-home',
      amount: 5200,
      date: '2026-09-16',
      category: 'Robocizna / Ekipa',
      paid: true,
      paymentMethod: 'Karta / Przelew',
      receiptNote: 'Uprawnienia SEP E+D protokół pomiarowy',
      hasAttachment: true,
    },
    {
      id: 'exp-7',
      title: 'Odpływ liniowy Viega Advantix Cleviva z syfonem',
      amount: 790,
      date: '2026-09-18',
      category: 'Materiały budowlane',
      roomId: 'room-bathroom',
      paid: true,
      paymentMethod: 'BLIK',
      receiptNote: 'Sklep internetowy ŁazienkiPlus',
      hasAttachment: true,
    },
    {
      id: 'exp-8',
      title: 'System poziomowania płytek (szczypce + 500 klipsów) i tarcza diamentowa',
      amount: 380,
      date: '2026-09-19',
      category: 'Narzędzia i sprzęt',
      roomId: 'room-bathroom',
      paid: true,
      paymentMethod: 'Karta / Przelew',
      receiptNote: 'Narzędzia Glazurnicze Rubi',
      hasAttachment: false,
    },
    {
      id: 'exp-9',
      title: 'Zaliczka na deski podłogowe Barlinek (jodełka)',
      amount: 2500,
      date: '2026-09-20',
      category: 'Materiały budowlane',
      roomId: 'room-living',
      paid: true,
      paymentMethod: 'Karta / Przelew',
      receiptNote: 'Zadatek na zamówienie specjalne',
      hasAttachment: true,
    },
  ],
  notifications: [
    {
      id: 'notif-1',
      title: 'Technologiczny czas schnięcia (Hydroizolacja)',
      message: 'Folia w płynie w łazience została naniesiona. Zostało 18h do osiągnięcia pełnej odporności przed kafelkowaniem. Nie wchodzić w obuwiu roboczym!',
      type: 'cure_time',
      timestamp: 'Przed chwilą',
      read: false,
      priority: 'high',
      stageId: 'st-4',
    },
    {
      id: 'notif-2',
      title: 'Harmonogram: Glazurnik rozpoczyna montaż 120x60',
      message: 'Etap układania płytek w łazience wystartował. Upewnij się, że system poziomowania i klej C2TE S1 są na miejscu budowy.',
      type: 'schedule',
      timestamp: 'Dziś, 08:30',
      read: false,
      priority: 'medium',
      stageId: 'st-5',
    },
    {
      id: 'notif-3',
      title: 'Alert budżetowy: 22.0% całkowitego budżetu wykorzystane',
      message: 'Wydano 20 910 PLN z planowanych 95 000 PLN. Wydatki na instalacje zamknęły się w granicach 96% szacunku.',
      type: 'budget',
      timestamp: 'Wczoraj, 18:00',
      read: true,
      priority: 'low',
    },
    {
      id: 'notif-4',
      title: 'Przypomnienie o pomiarze wilgotności posadzki',
      message: 'Przed dostawą deski warstwowej do salonu wykonaj badanie wilgotnościomierzem CM (max 1.8% dla jastrychu cementowego).',
      type: 'qa',
      timestamp: '2 dni temu',
      read: true,
      priority: 'medium',
      stageId: 'st-8',
    },
  ],
  qaChecklist: [
    {
      id: 'qa-1',
      roomId: 'room-bathroom',
      stageCategory: 'insulation',
      title: 'Ciągłość taśm i mankietów hydroizolacyjnych',
      standardNorm: 'Wytyczne ITB 402/2004',
      severity: 'critical',
      status: 'passed',
      measuredValue: '2 warstwy, mankiety wokół rur fi 50 i 110',
      toleranceGuide: 'Brak jakichkolwiek prześwitów podłoża i pęcherzy powietrza',
      inspectionTips: 'Sprawdź narożniki pionowe i poziome ze szczególnym uwzględnieniem strefy wokół baterii podtynkowej.',
    },
    {
      id: 'qa-2',
      roomId: 'room-bathroom',
      stageCategory: 'installation',
      title: 'Spadek posadzki w kabinie Walk-In min. 2.0%',
      standardNorm: 'PN-EN 12056-2:2002',
      severity: 'critical',
      status: 'passed',
      measuredValue: '2.3% w kierunku rynny',
      toleranceGuide: 'Minimum 1.5% do 2.5% w stronę koryta odpływowego',
      inspectionTips: 'Sprawdź poziomicą elektroniczną lub wylej 0.5L wody, aby potwierdzić brak zastoin na płytkach.',
    },
    {
      id: 'qa-3',
      roomId: 'room-bathroom',
      stageCategory: 'installation',
      title: 'Próba ciśnieniowa instalacji PEX 10 bar',
      standardNorm: 'PN-EN 806-4:2010',
      severity: 'critical',
      status: 'passed',
      measuredValue: '10.2 bar przez 24h bez spadku',
      toleranceGuide: 'Maksymalny spadek ciśnienia: 0.1 bar po 24 godzinach',
      inspectionTips: 'Zrób zdjęcie manometru na początku i na końcu próby przed zakryciem bruzd.',
    },
    {
      id: 'qa-4',
      roomId: 'room-living',
      stageCategory: 'masonry',
      title: 'Kąty proste (90°) narożników pod zabudowę kuchenną',
      standardNorm: 'PN-B-10110:2005 (Kątowość tynków)',
      severity: 'important',
      status: 'pending',
      measuredValue: 'Do weryfikacji po gładziach',
      toleranceGuide: 'Odchyłka max 2mm na długości ramienia kątownika 100cm',
      inspectionTips: 'Kluczowe w miejscu styku szafek kuchennych i wyspy, inaczej powstaną nieestetyczne szpary przy blatach.',
    },
    {
      id: 'qa-5',
      roomId: 'room-living',
      stageCategory: 'flooring',
      title: 'Równość podłoża pod deskę klejoną',
      standardNorm: 'DIN 18202 Tabela 3 linia 4',
      severity: 'important',
      status: 'pending',
      measuredValue: 'Szacowane 1.5mm',
      toleranceGuide: 'Maksymalna szczelina 2.0 mm pod łatą 200cm',
      inspectionTips: 'Połóż łatę 2m w różnych kierunkach i sprawdź szczelinomierzem klinowym.',
    },
  ],
};

export const DEFAULT_RENOVATION_PROJECT = INITIAL_RENOVATION_PROJECT;
